### PR TITLE
Complete support for Windows & Linux

### PR DESCRIPTION
**Pull request by mytja**
Hey
Sorry, I have to bother you, but I found this issue... It somehow got lost during merges and checkouts...
I will also merge new translations into this, so don't merge it yet.
Thanks

### CODE REVIEW

**Comment by mytja** [comment]
Hello, @bdlukaa and @alexmercerind !
Here is a final & working version of Harmonoid. Everything is working. All I have to do, is to try to build for Linux and for Android (Android currently can't extract artworks for some reason, and Android needs some UI improvements).
Thanks

**Comment by alexmercerind** [comment]
@mytja I'm currently working on different playback backend for Windows. I feel Android one already worked correctly (or does it)?

**Comment by mytja** [comment]
> @mytja I'm currently working on different playback backend for Windows. I feel Android one already worked correctly (or does it)?

Yes, it worked correctly, and it still works as intended...

**Comment by alexmercerind** [comment]
@mytja are we ready to merge this.

**Comment by mytja** [comment]
> @mytja are we ready to merge this.

I have to add Linux integration before we can merge it.
This is currently blocking me: https://github.com/alexmercerind/flutter_media_metadata/issues/14

**Comment by mytja** [comment]
Hey, @bdlukaa 
I am ready, and I think we should merge it... :tada:

**Comment by bdlukaa** [comment]
as you wish

**Pull request merged**
